### ISSUE TITLE
Print Order resulting in huge number of filament swaps.

### ISSUE THREAD

**Issue by tobiasv1337** [Kower999/FilamentChangeByMesh#1]
Thank you for your Cura Plugin,
I was looking for an option to do some multicolor prints on my Ender 3 with loads of M600 manual filament swaps. I was surprised to find out that Cura has no built-in solution for that. But then I found your Reddit post with your plugin, which looked really promising.

I have only one minor problem which is actually more a problem in Cura itself but makes your plugin less useful.

I have a multicolored part with 3 separate stl files. With all the different multicolored layers this would result in 127 inserted filament changes from your plugin. Which takes quite some time, but is actually quite reasonable.

I have to print these parts multiple times. I was hoping that somehow I could convince Cura to print each mesh layer of one color of all parts before switching color and printing the whole layer with color2. This way I would only need 127 filament changes (as if I only wanted to print a single part) eventhough I would print multiple parts at the same time and shouldn't result in major issues?
Therefore, every color would only be used once for each layer if needed.

I've tried adding 2 of the same multicolor parts and sliced them with Cura with your plugin, and unfortunately it resulted in 253 filament changes.

It looks like Cura is always printing one part at a time and therefore the filament changes multiply per object.

I've tried to find options in Cura to manually set the printing order of the meshes but found no option to. Tricks like removing and reading files to Cura which supposedly worked in the past didn't work either.

Do you know how I could fix that? This would make your printing multicolor with your plugin so much more effective.

I guess ordering the gcode post slicing within your python script is probably too difficult?

**Comment by tobiasv1337** [comment]
I've now found kind of a solution.
It looks like that it might be a working solution to import the stl files into a cad program, multiply the objects there and export each color object group as one stl file.
It's definitely not a very comfortable workaround but it seems to be working,

Is there a better way to achieve the same result?

**Comment by Kower999** [comment]
Hi Tobias,
solution you have found yourself is in fact correct way to avoid of multiply of filament changes when you need to print copies of object in one print session. 

This script works as simple as it inserts filament change G-Code to each part of G-Code where its needed. Your advice to group/order same color printing G-code is good idea and not impossible. I need to rethink it if it would not lead into some head crashes into model but if you are correct that Cura print's whole model/stl per layer then it should be safe to do such a grouping to avoid anoing additional multiply of object in CAD program.

**Comment by Kower999** [comment]
Update:

After deeper thinking about issue and solution i need to state its definitely not possible to do groupping/reordering of Gcode to avoid excessive filament changes. 
There two possible outcomes of such action:

1. If user uses relative print head positioning this would lead into total mess of print because relative positions would not be correct after Gcode reordering.

2. If user uses absolute positioning its bit better case but it would result in ineffective travel routes which would lead into wrong positions to start printing after travel move if Gcode would be reordered. That would for sure lead into longer print time and possibly into spilling filament at wrong place.

So sadly only solution to avoid multiplying filament changes when printing object more than once in one session is your approach you already found yourself as grouping same color parts into one file in CAD program.
